### ISSUE TITLE
Topology Was Destroyed

### ISSUE THREAD

**Issue by baskerville** [kcbanner/connect-mongo#175]
Any idea what might be causing this error:
```
MongoError: topology was destroyed
    at Server.update (./runtime/repo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:823:49)
    at Server.update (./runtime/repo/node_modules/mongodb/lib/server.js:316:17)
    at updateDocuments (./runtime/repo/node_modules/mongodb/lib/collection.js:652:19)
    at Collection.update (./runtime/repo/node_modules/mongodb/lib/collection.js:680:10)
    at ./runtime/repo/node_modules/connect-mongo/lib/connect-mongo.js:359:18
    at MongoStore.getCollection (./runtime/repo/node_modules/connect-mongo/lib/connect-mongo.js:217:11)
    at MongoStore.set (./runtime/repo/node_modules/connect-mongo/lib/connect-mongo.js:357:10)
    at Session.save (./runtime/repo/node_modules/express-session/session/session.js:71:25)
    at Session.save (./runtime/repo/node_modules/express-session/index.js:327:15)
    at ServerResponse.end (./runtime/repo/node_modules/express-session/index.js:285:21)
    at ReadStream.onend (_stream_readable.js:505:10)
    at ReadStream.g (events.js:199:16)
    at ReadStream.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
?

**Comment by baskerville** [comment]
Not sure if it might help but it seems that `db.sessions.count()` constantly grows by about one item per second.

**Comment by baskerville** [comment]
The problem seems to originate from `express-session`, sorry.

**Comment by dalelotts** [comment]
Can you provide any more information in case someone else encounters this error (I just did!)

**Comment by baskerville** [comment]
Sure : my problem was solved by setting the *saveUninitialized* option to *false*.
