### ISSUE TITLE
set name throw MongoError: E11000 duplicate key error index: nwitter.sessions.$sid_1 dup key: { : null }

### ISSUE THREAD

**Issue by zwb-ict** [kcbanner/connect-mongo#177]
I set name 'nw.sid' as follows:

```
.use(require('cookie-parser')())
.use(require('express-session')({
            name: 'nw.sid',
            store: new mongoSessionStore({ url: configDB.url }),
            resave: false,
            saveUninitialized: true,
            secret: credentials.cookieSecret,
            cookie: {
                secure: true,
                maxAge: credentials.maxAge
            }}))
```

then get this error message:

> Nwitter started on http://localhost:3000; press Ctrl-C to terminate.
GET / 304 61.518 ms - -
MongoError: E11000 duplicate key error index: nwitter.sessions.$sid_1 dup key: { : null }
    at toError (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/connect-mongo/node_modules/mongodb/lib/utils.js:113:11)
    at /Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/connect-mongo/node_modules/mongodb/lib/collection.js:657:67
    at /Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:730:13
    at Callbacks.emit (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
    at null.messageHandler (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:219:23)
    at Socket.<anonymous> (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/express/lib/response.js:700:10)
    at ServerResponse.res.contentType.res.type (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/express/lib/response.js:537:15)
    at ServerResponse.send (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/express/lib/response.js:129:14)
    at fn (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/express/lib/response.js:934:10)
    at Immediate._onImmediate (/Users/zwb/Documents/Code-Learning/node-workspace/nwitter/node_modules/express-handlebars/lib/utils.js:26:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

my package.json:
```
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.12.4",
    "connect": "^2.29.2",
    "connect-flash": "^0.1.1",
    "connect-mongo": "^0.8.1",
    "cookie-parser": "^1.3.4",
    "express": "^4.12.3",
    "express-handlebars": "^2.0.1",
    "express-session": "^1.11.2",
    "mongoose": "^4.0.3",
    "morgan": "^1.5.3",
    "passport": "^0.2.1",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^1.0.0",
    "passport-remember-me": "0.0.1"
  },
```

**Comment by keyiis** [comment]
@zwb-ict Are you resolver?
