### ISSUE TITLE
Module throws TypeError: Cannot read property 'hasListIndexesCommand' of undefined

### ISSUE THREAD

**Issue by Redsandro** [kcbanner/connect-mongo#181]
When this module is first instantiated, it throws an error:

`TypeError: Cannot read property 'hasListIndexesCommand' of undefined`

Stack: 

```
/var/nodejs/test/node_modules/connect-mongo/lib/connect-mongo.js:134
          throw err;
                ^
TypeError: Cannot read property 'hasListIndexesCommand' of undefined
    at Collection.listIndexes (/var/nodejs/test/node_modules/mongodb/lib/mongodb/collection/index.js:84:49)
    at Db.indexInformation (/var/nodejs/test/node_modules/mongodb/lib/mongodb/db.js:1604:25)
    at Db.ensureIndex (/var/nodejs/test/node_modules/mongodb/lib/mongodb/db.js:1471:8)
    at Collection.ensureIndex (/var/nodejs/test/node_modules/mongodb/lib/mongodb/collection/index.js:68:11)
    at connectionReady (/var/nodejs/test/node_modules/connect-mongo/lib/connect-mongo.js:142:27)
    at Db.collection (/var/nodejs/test/node_modules/mongodb/lib/mongodb/db.js:498:20)
    at initWithNativeDb (/var/nodejs/test/node_modules/connect-mongo/lib/connect-mongo.js:208:20)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

Called like so:

```
var session			= require('express-session')
  , MongoStore		= require('connect-mongo')(session)
  , sessionStore	= new MongoStore({
			db			: mongoDb.client,
			collection	: config.mongodb.collections.adminSess
		})
  , sessionWare		= session({
			secret		: 'ICanHasSecret',
			store		: sessionStore,
			resave		: true,
			saveUninitialized: false
		});
```

Because this: https://github.com/kcbanner/connect-mongo/blob/master/lib/connect-mongo.js#L142

__Workaround:__

```
  , sessionStore	= new MongoStore({
			db			: mongodb.client,
			collection	: mongodb.collections.sessions,
			autoRemove	: 'ignore'
		})
```

(Note the `autoRemove  : 'ignore'`) so that `connect-mongo` starts as idle, not immediately doing db stuff.

---

I suspect the connection to the MongoDB adapter is not fully complete yet when both MongoDB and connect-mongo are required in the same module. Perhaps the `ensureIndex` should not run until after a minute, or until some connection check evals to true.

I suspect this was the same error as https://github.com/kcbanner/connect-mongo/issues/159

**Comment by jdesboeufs** [comment]
What is `mongoDb.client` in your code?

**Comment by Redsandro** [comment]
@jdesboeufs I had no idea you replied, and then I forgot about it. The notification must have slipped past me 12 months ago. Client was probably a MongoDB connection or pool. I'm using `dbPromise` now.

**Comment by HarshitaS1712** [comment]
TypeError: Cannot read property 'indexOf' of undefined
    at Function.handle (C:\project\TRY\loginapp-master\node_modules\express\lib\
router\index.js:140:27)
    at new router (C:\project\TRY\loginapp-master\node_modules\express\lib\route
r\index.js:46:12)
    at Object.<anonymous> (C:\project\TRY\loginapp-master\routes\products.js:14:
16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

why this error?
