### ISSUE TITLE
Unhandled rejection MongoError: cannot connect to server

### ISSUE THREAD

**Issue by gaoerjun** [kcbanner/connect-mongo#210]
I meet a problem that I do not know why it happened. When I start to run my app.js ,it throw errors like below ：
```javascript
Unhandled rejection MongoError: cannot connect to server
    at Collection.listIndexes (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1725:11)
    at indexInformation (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1569:25)
    at Db.indexInformation (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1533:44)
    at ensureIndex (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1028:8)
    at Db.ensureIndex (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/db.js:1004:44)
    at ensureIndex (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1785:13)
    at Collection.ensureIndex (/Users/gaoerjun/Documents/front-end-website/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1773:44)
    at tryCatcher (/Users/gaoerjun/Documents/front-end-website/node_modules/bluebird/js/main/util.js:24:31)
    at ret [as ensureIndexAsync] (eval at <anonymous> (/Users/gaoerjun/Documents/front-end-website/node_modules/bluebird/js/main/promisify.js:154:12), <anonymous>:13:39)
    at MongoStore.setAutoRemoveAsync (/Users/gaoerjun/Documents/front-end-website/node_modules/connect-mongo/src/index.js:123:40)
    at MongoStore.handleNewConnectionAsync (/Users/gaoerjun/Documents/front-end-website/node_modules/connect-mongo/src/index.js:116:18)
    at MongoStore (/Users/gaoerjun/Documents/front-end-website/node_modules/connect-mongo/src/index.js:95:26)
    at Object.<anonymous> (/Users/gaoerjun/Documents/front-end-website/app/app.js:33:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)

```

Here is my app.js : 
```javascript
'use strict';

var PORT_LISTENER = 3001;
console.log('I am listening to this port: http://localhost:%s', PORT_LISTENER);

var express = require('express'),
    http = require('http'),
    path = require('path');

var appConfig = require('./config/appConfig.json');
const session = require('express-session');
const MongoStore = require('connect-mongo')(session);

require(appConfig.directories.modelsDir+"/blob_model.js");

var mongoose = require("mongoose");
mongoose.connect('mongodb://localhost/test');
var app = express();
// all environments
app.set('port', process.env.PORT || PORT_LISTENER);
app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.use(express.favicon());
app.use(express.logger('dev'));
app.use(express.bodyParser({ keepExtensions: true, uploadDir: path.join(__dirname, appConfig.directories.publicDir) }));
app.use(express.cookieParser('my v3ry s3cr3t C00k1e k3y d0nt y0u th1nk?'));
app.use(session({
    secret: 'foo',
    store: new MongoStore(
        {
            db:mongoose.connection.db,
            collection:"session"
        }
    )
}));


//routes
require('./routes/index')(app);

app.use(app.router);
app.use(express.static(path.join(__dirname, appConfig.directories.publicDir)));

app.use(function (req, res, next) {
    console.log('req.body: ' + JSON.stringify(req.body));
    next();
});

// development only
if ('development' === app.get('env')) {
    app.use(express.errorHandler());
}


http.createServer(app).listen(app.get('port'), function () {
    console.log('Express server listening on port ' + app.get('port'));
});
```
The errors are throw from here 
```javascript
app.use(session({
    secret: 'foo',
    store: new MongoStore(
        {
            db:mongoose.connection.db,
            collection:"session"
        }
    )
}));
```

```javascript
new MongoStore({});
```

My mongodb is running well ,I don`t know where is the wrong place .How can fix this it ? Thank you ~

**Comment by jdesboeufs** [comment]
You should try this:
```js
app.use(session({
    secret: 'foo',
    store: new MongoStore(
        {
            mongooseConnection: mongoose.connection,
            collection: 'session'
        }
    )
}));
```

**Comment by gaoerjun** [comment]
@jdesboeufs  Thank you very much . It`s ok now ! thanks again ~

**Comment by jdesboeufs** [comment]
:dancers:
