### ISSUE TITLE
Error connecting to mongodb for the second time

### ISSUE THREAD

**Issue by avihebbar** [kcbanner/connect-mongo#216]
Hi,
I am trying to use the MongoStore with MongoDB connection string. Whenever I set up a  MongoStore with a new collection, it works fine. But after the app restarts, I get the following error. 

> /home/workspace/test/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
        ^

> TypeError: Cannot read property 'length' of undefined
  at processResults (/home/workspace/test/node_modules/mongodb/lib/mongodb/db.js:1603:31)
  at /home/workspace/test/node_modules/mongodb/lib/mongodb/db.js:1641:20
  at /home/workspace/test/node_modules/mongodb/lib/mongodb/db.js:1179:7
  at /home/workspace/test/node_modules/mongodb/lib/mongodb/db.js:1912:9
  at Server.Base._callHandler (/home/workspace/test/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
  at /home/workspace/test/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
  at [object Object].MongoReply.parseBody (/home/workspace/test/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
  at [object Object].<anonymous> (/home/workspace/test/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)
  at emitOne (events.js:77:13)
  at [object Object].emit (events.js:169:7)
  at [object Object].<anonymous> (/home/workspace/test/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
  at emitTwo (events.js:87:13)
  at [object Object].emit (events.js:172:7)
  at Socket.<anonymous> (/home/workspace/test/node_modules/mongodb/lib/mongodb/connection/connection.js:439:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20) 

The issue gets fixed if I change the **collection** in the options, but the same issue repeats after a restart. 

Anything that I am missing that can fix this issue?

Thanks,

**Comment by avihebbar** [comment]
I figured it out. Sorry it was some issue with the version on mongodb
