### ISSUE TITLE
tingodb can not use

### ISSUE THREAD

**Issue by blitheinsz** [kcbanner/connect-mongo#220]
my source code:--------

var Engine = require('tingodb')();
var session = require('express-session');
var app = express();
var db = new Engine.Db('./public/data', {});
var MongoStore = require('connect-mongo/es5')(session);
app.set('db',db);
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(session({
    cookie: { maxAge: 3600000 },
    secret:"test",
    store: new MongoStore({db:db})
    }));

---------------------------------------------------------------------------------------
E:\GitHome\html5\compuslite\node_modules\connect-mongo\src-es5\index.js:121
                throw new Error('Connection strategy not found');
                      ^
Error: Connection strategy not found
    at new MongoStore (E:\GitHome\html5\compuslite\node_modules\connect-mongo\sr
c-es5\index.js:121:23)
    at Object.<anonymous> (E:\GitHome\html5\compuslite\app.js:29:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\GitHome\html5\compuslite\bin\www:7:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by jdesboeufs** [comment]
TingoDB is not officially supported by `connect-mongo`.
If someone want to fix that, I'll be happy to accept a PR.
